### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by mikechapman101** [bbc/gatling-load-tests#21]
I want us to show a working demo of some sort. What do we need to show? What screens, graphs, inputs/outputs, monitoring, visualisation of a build as it progresses through each step including perf testing steps.

Also need to consider where we run a demo from, proxies, remote sharing etc

**Comment by aidylewis** [comment]
We can walk through a test and a jenkins job config and show the graphs in real time. This can be done through a proxy and we can demo it through a TV in a meeting room.

**Comment by aidylewis** [comment]
I've downloaded a Docker image with Jenkins pre-installed. I'll write a docker file to add the Gatling Jenkins plugin.

**Comment by aidylewis** [comment]
Gatling plugin has been integrated into Jenkins that includes performance trends and implementation reports.

**Comment by mikechapman101** [comment]
Three things I would like to see as part of the demo please:

1) A walk-through talk end-to-end (perhaps accompanied by bullet-points on a slide?) of how the system should work and how we can integrate it into a product team's current development/build cycle

2) Some code checked in to source control (something simple), the build system then being triggered, building, deploying, and then something (cron/Jenkins) triggering an automated load test, delivering the results either output to screen or recorded in a DB for viewing

3) Some (a less/more performant version of the) code being checked in.... with the results demonstrating the delta in performance and flagging if it is less/more performant

**Comment by aidylewis** [comment]
1. I was going to walk through a sample test which will demonstrate a number of features in Gatling, including CSS selectors with are normally only found in functional web tools. CT for example makes us battle with XPath in order to retrieve HTML object values. I will demo here the Grafana graphs and InfluxDB.

2.  I am pulling down our Github BBC load-tests as part of our job configuration. The demo will be triggered with the 'build now' button which will run the sample test. I can also show a timed build triggered through cron in Jenkins. Here we will see the Gatling plugin at work displaying performance trends. The JS reports all also produced in Jenkins.

3. Unless I create my own application and run a local web server, I am not sure I am able to do this. The trend at the moment will be a flat line as the tests are run straight after each other.

**Comment by aidylewis** [comment]
I am now thinking the tests should be triggered by a passing acceptance test build. This is unrealistic for  demonstration purposes so I'll trigger them from a git push.

**Comment by aidylewis** [comment]
I am ready to demo the graphing and the Jenkins Gatling plugin. Feel free to re-open this if you want anything else covered.

**Comment by aidylewis** [comment]
1. Create app that uses an LDP API
2. Add sleep in a route which slows down response times
3. Send email when response time threshold is achieved

**Comment by aidylewis** [comment]
the app is here:  https://gatling-demo-app.herokuapp.com/
I am using the BBC locator API to retrieve a geographical location from a geoname id
https://gatling-demo-app.herokuapp.com/locator/2636432
https://gatling-demo-app.herokuapp.com/locator/2652221

**Comment by aidylewis** [comment]
The test is [here](https://github.com/aidylewis/gatling-demo-test)
